name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-webserver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build Docker image for Webserver
        run: |
          docker build -t ghcr.io/soep1/profilepage:latest -f ./webdev-showcase-studentversie/UC1-profielpagina/Showcase-profielpagina/Dockerfile .
          docker push ghcr.io/soep1/profilepage:latest
          
          